// tslint:disable:no-magic-numbers
enum MESSAGE_TYPE {
  QUERY_LATEST,
  QUERY_ALL,
  RESPONSE_BLOCKCHAIN,
}

const CONVERSIONS = {
  sec: 1000,
  min: 1000 * 60,
};

const MINING = {
  BLOCK_GENERATION_INTERVAL: 5,
  DIFFICULTY_ADJUSTMENT_INTERVAL: 5,
  DIFFICULTY_ADJUSTMENT_RATE: 1,
  INTERVAL_RANGE: 2,
};

const NATIVE_TOKEN = {
  ID: '18f6708186322cad57b5cf28a015e25d2bfa932f6379e01002e9b3f9608ab48f',
  NAME: 'native token',
  DESCRIPTION: 'native token',
  DECIMALS: 0,
  TOTAL: 10000,
};

const STATUS_CODE = {
  UNAUTHORIZED: 401,
  BAD_REQUEST: 400,
  METHOD_NOT_ALLOWED: 405,
};

const RECONNECT_TIME = 3000;

const LEVY_RATE = 0.05;

const CASHBACK_RATE = 0.03;

// tslint:enable:no-magic-numbers

export {
  MESSAGE_TYPE,
  CONVERSIONS,
  MINING,
  NATIVE_TOKEN,
  STATUS_CODE,
  RECONNECT_TIME,
  LEVY_RATE,
  CASHBACK_RATE,
};
